name: Run Bun Script Daily

on:
  schedule:
    - cron: '0 13 * * *'    # 6:00 AM PDT
    - cron: '29 13 * * *'   # 6:29 AM PDT

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Run script
        run: bun run index.ts
